import { FileCheck2, Lock, Printer } from 'lucide-react';
import { useEffect, useState } from 'react';

import { toast } from 'sonner';
import { Badge } from '~/components/ui/badge';
import { Button } from '~/components/ui/button';
import { Card, CardContent } from '~/components/ui/card';
import { Checkbox } from '~/components/ui/checkbox';
import { Dialog, DialogContent, DialogDescription, DialogHeader, DialogTitle } from '~/components/ui/dialog';
import { Input } from '~/components/ui/input';
import { Label } from '~/components/ui/label';
import {
    getAllegationsByMatter,
    getEvidenceByMatter,
    getInterviewsByMatter,
    getTimelineEventsByMatter,
} from '~/data/selectors';
import { AutoFillPanel } from '~/features/reportAutoFill';
import { draftToCustomReportSections, draftToReportSections } from '~/features/reportAutoFill/mapping/reportHandoff';
import type { ReportDraft } from '~/features/reportAutoFill/types/reportAutoFill';
import { useFindingsStore, useInvestigationFindings } from '~/hooks/use-findings-store';
import { useInvestigation } from '~/hooks/use-investigation';
import { defaultReportConfig, useReportConfig, useReportStatus, useReportStore } from '~/hooks/use-report-store';
import { buildReport, reportSectionDefs, type ReportSection } from '~/lib/report';
import type { Allegation, Evidence as EvidenceItem, InterviewWithWitness, TimelineEvent } from '~/types';

function formatDate(iso: string) {
    return new Date(iso).toLocaleDateString('en-GB', { day: 'numeric', month: 'short', year: 'numeric' });
}

function ReportBody({
    title,
    matter,
    sections,
    finalMode,
}: {
    title: string;
    matter: ReturnType<typeof useInvestigation>;
    sections: ReportSection[];
    finalMode: boolean;
}) {
    return (
        <Card className="print-area">
            <CardContent className="mx-auto max-w-3xl space-y-6 p-8">
                <header className="space-y-1 border-b pb-6 text-center">
                    <p className="text-muted-foreground font-mono text-xs tracking-widest uppercase">
                        {finalMode ? 'Final investigation report' : 'Investigation report — draft preview'}
                    </p>
                    <h2 className="text-xl font-semibold tracking-tight">{title}</h2>
                    <p className="text-muted-foreground text-sm">
                        {matter.referenceNumber} · {matter.client}
                    </p>
                    <p className="text-muted-foreground text-xs">
                        Investigator: {matter.investigator} · Opened {formatDate(matter.openedAt)} · Target {formatDate(matter.targetCompletionDate)}
                        {finalMode ? ` · Issued ${formatDate(new Date().toISOString().slice(0, 10))}` : ''}
                    </p>
                </header>

                {sections.length === 0 && (
                    <p className="text-muted-foreground py-8 text-center text-sm">No sections selected — include at least one section.</p>
                )}

                {sections.map((section) => (
                    <section key={section.id} className="space-y-2">
                        <h3 className="text-sm font-semibold tracking-wide uppercase">{section.heading}</h3>
                        {section.paragraphs.map((paragraph, index) => (
                            <p key={index} className="text-muted-foreground text-sm leading-relaxed">
                                {paragraph}
                            </p>
                        ))}
                        {section.bullets.length > 0 && (
                            <ul className="list-disc space-y-1 pl-5">
                                {section.bullets.map((bullet, index) => (
                                    <li key={index} className="text-muted-foreground text-sm leading-relaxed">
                                        {bullet}
                                    </li>
                                ))}
                            </ul>
                        )}
                    </section>
                ))}

                <footer className="text-muted-foreground border-t pt-4 text-center text-xs">
                    Mock report generated by the prototype — no real documents are produced or stored.
                </footer>
            </CardContent>
        </Card>
    );
}

export default function Reports() {
    const matter = useInvestigation();
    const savedFindings = useInvestigationFindings(matter.id).findings;
    const reportStatus = useReportStatus(matter.id);
    const config = useReportConfig(matter.id);
    const markFinal = useReportStore((state) => state.markFinal);
    const updateConfig = useReportStore((state) => state.updateConfig);
    const toggleSection = useReportStore((state) => state.toggleSection);
    const setAutoFill = useReportStore((state) => state.setAutoFill);
    const setCustomAutoFill = useReportStore((state) => state.setCustomAutoFill);
    const autoFillValues = useReportStore((state) => state.autoFillByInvestigation[matter.id]);
    const customAutoFillSections = useReportStore((state) => state.customAutoFillByInvestigation[matter.id]);
    const [mode, setMode] = useState<'customize' | 'final'>('customize');
    const [confirmingFinal, setConfirmingFinal] = useState(false);
    const [data, setData] = useState<{
        allegations: Allegation[];
        interviews: InterviewWithWitness[];
        evidenceItems: EvidenceItem[];
        events: TimelineEvent[];
    } | null>(null);

    useEffect(() => {
        let cancelled = false;
        Promise.all([
        getAllegationsByMatter(matter.id),
        getInterviewsByMatter(matter.id),
        getEvidenceByMatter(matter.id),
        getTimelineEventsByMatter(matter.id),
        ]).then(([allegations, interviews, evidenceItems, events]) => {
            if (!cancelled) {
                setData({ allegations, interviews, evidenceItems, events });
                useFindingsStore.getState().hydrate(matter.id, allegations);
            }
        });
        void useReportStore.getState().load(matter.id);
        return () => {
            cancelled = true;
        };
    }, [matter.id]);

    if (!data) {
        return <p className="text-muted-foreground text-sm">Assembling report…</p>;
    }

    const isFinal = reportStatus === 'final';
    const sections = buildReport({
        matter,
        ...data,
        savedFindings,
        config: config ?? defaultReportConfig,
        autoFill: autoFillValues,
        autoFillSections: customAutoFillSections,
    });

    const handleAutoFillAccept = (draft: ReportDraft) => {
        setAutoFill(matter.id, draftToReportSections(draft));
        setCustomAutoFill(matter.id, draftToCustomReportSections(draft));
        toast.success('Auto-fill accepted', {
            description: `${matter.referenceNumber} — mapped content was appended to the report sections.`,
        });
    };
    const reportTitle = config.title.trim() || matter.title;

    const finalize = () => {
        markFinal(matter.id);
        setConfirmingFinal(false);
        toast.success('Report marked as final', { description: `${matter.referenceNumber} — customization is now locked.` });
    };

    return (
        <div className="space-y-4">
            {mode === 'customize' && <AutoFillPanel matterId={matter.id} onAccept={handleAutoFillAccept} />}
            <Dialog open={confirmingFinal} onOpenChange={setConfirmingFinal}>
                <DialogContent className="sm:max-w-md">
                    <DialogHeader>
                        <DialogTitle>Mark report as final?</DialogTitle>
                        <DialogDescription>
                            This locks the report structure and customization for {matter.referenceNumber}. The mock action cannot be undone in this
                            session.
                        </DialogDescription>
                    </DialogHeader>
                    <div className="flex justify-end gap-2">
                        <Button variant="outline" size="sm" onClick={() => setConfirmingFinal(false)}>
                            Cancel
                        </Button>
                        <Button size="sm" onClick={finalize}>
                            Mark as final
                        </Button>
                    </div>
                </DialogContent>
            </Dialog>

            <div className="flex flex-wrap items-center justify-between gap-3 print:hidden">
                <div className="flex items-center gap-2">
                    <Badge variant={isFinal ? 'default' : 'outline'} className="gap-1">
                        <FileCheck2 className="size-3.5" />
                        {isFinal ? 'Final' : 'Draft'}
                    </Badge>
                    <span className="text-muted-foreground text-xs">
                        {mode === 'customize' ? 'Customize the report; the preview updates live.' : 'Mock final report view.'}
                    </span>
                </div>
                <div className="flex flex-wrap gap-2">
                    <Button variant="outline" size="sm" onClick={() => window.print()}>
                        <Printer className="size-4" /> Print / PDF
                    </Button>
                    {mode === 'customize' ? (
                        <>
                            <Button variant="outline" size="sm" onClick={() => setMode('final')}>
                                Preview final view
                            </Button>
                            {!isFinal && (
                                <Button size="sm" onClick={() => setConfirmingFinal(true)}>
                                    Mark as final
                                </Button>
                            )}
                        </>
                    ) : (
                        <Button variant="outline" size="sm" onClick={() => setMode('customize')}>
                            Back to editor
                        </Button>
                    )}
                </div>
            </div>

            {mode === 'customize' ? (
                <div className="grid items-start gap-4 lg:grid-cols-[300px_1fr]">
                    <Card>
                        <CardContent className="space-y-5 p-5">
                            <div className="flex items-center justify-between">
                                <h3 className="text-sm font-semibold">Customize report</h3>
                                {isFinal && (
                                    <span className="text-muted-foreground inline-flex items-center gap-1 text-xs">
                                        <Lock className="size-3" /> Locked
                                    </span>
                                )}
                            </div>
                            <div className="space-y-1.5">
                                <Label htmlFor="report-title">Report title</Label>
                                <Input
                                    id="report-title"
                                    value={config.title}
                                    disabled={isFinal}
                                    placeholder={matter.title}
                                    onChange={(event) => updateConfig(matter.id, { title: event.target.value })}
                                />
                            </div>
                            <div className="space-y-1.5">
                                <Label htmlFor="exec-summary">Executive summary</Label>
                                <textarea
                                    id="exec-summary"
                                    value={config.executiveSummary}
                                    disabled={isFinal}
                                    rows={5}
                                    placeholder="Optional summary shown before section 1…"
                                    onChange={(event) => updateConfig(matter.id, { executiveSummary: event.target.value })}
                                    className="placeholder:text-muted-foreground focus-visible:ring-ring w-full rounded-md border bg-transparent px-3 py-2 text-sm shadow-xs focus-visible:ring-2 focus-visible:outline-none disabled:cursor-not-allowed disabled:opacity-50"
                                />
                            </div>
                            <div className="space-y-2">
                                <Label>Sections</Label>
                                {reportSectionDefs.map((section) => (
                                    <label key={section.id} className="flex items-center gap-2 text-sm">
                                        <Checkbox
                                            checked={config.includedSections[section.id] ?? true}
                                            disabled={isFinal}
                                            onCheckedChange={() => toggleSection(matter.id, section.id)}
                                        />
                                        {section.heading}
                                    </label>
                                ))}
                            </div>
                            <p className="text-muted-foreground text-xs">Customizations are held in mock state for this session.</p>
                        </CardContent>
                    </Card>
                    <ReportBody title={reportTitle} matter={matter} sections={sections} finalMode={false} />
                </div>
            ) : (
                <ReportBody title={reportTitle} matter={matter} sections={sections} finalMode={true} />
            )}
        </div>
    );
}
